// src/app/pages/design-page/design-page.component.ts
import { Component, OnInit } from '@angular/core';
import { DesignEntryRows } from '../../design';

@Component({
  selector: 'app-design-page',
  templateUrl: './design-page.component.html',
  styleUrls: ['./design-page.component.scss']
})
export class DesignPageComponent implements OnInit {
  entryRows = DesignEntryRows;

  constructor() { }

  ngOnInit(): void {
  }

}

<app-portfolio-header
  title="Design"
  caption="Despite my passion for technical code development, I don't mind getting my hands dirty in the world of digital design.
  I am by no means an artist, but I have an eye for what looks good and what users would think is functional, yet attractive.
  I have integrated this perspective with how I design websites, games, logos, and social content to create my own digital works of art."
></app-portfolio-header>
<div *ngFor="let row of entryRows" id="div-entry-row"  class="flex-margin" fxLayout="row" fxLayoutAlign="space-between">
  <app-design-entry [entry]="row[0]"></app-design-entry>
  <app-design-entry [entry]="row[1]"></app-design-entry>
</div>

// src/pages/DesignPage.vue
<template>
  <Header />
  <!-- BANNER -->
  <Banner graphics="Design">
    <template v-slot:title>
      Design<br><span>Portfolio</span>
    </template>
    <template v-slot:content>
      <div class="banner__caption">
        Although I am by no means an artist, I have an eye for what looks good
        and what users think is functional, yet attractive. I have integrated this
        skill into how I design everything from websites to logos.
      </div>
    </template>
  </Banner>
  <!-- CONTENT -->
  <div class="content">
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import Header from "@/components/Header.vue";
import Banner from "@/components/Banner.vue";

export default defineComponent({
  name: "DesignPage",
  components: {
    Header,
    Banner
  },
  setup() {
  }
});
</script>

<style lang="scss" scoped>
.banner__caption {
  @include mix-banner-caption;
}

.content {
  @include mix-content;
}
</style>
